<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Ardalis.SharedKernel" />
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" ExcludeAssets="contentFiles" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="SQLite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Vogen" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Hmz.Kolafi.Core\Hmz.Kolafi.Core.csproj" />
    <ProjectReference Include="..\Hmz.Kolafi.UseCases\Hmz.Kolafi.UseCases.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Data\Migrations\" />
  </ItemGroup>
</Project>
